"""initial schema

Revision ID: 6d82e00ff8d9
Revises: 
Create Date: 2026-02-28 17:23:08.225362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d82e00ff8d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educational_content', schema=None) as batch_op:
        batch_op.alter_column('chapter_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('histamine_liberator',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('dao_blocker',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'usda_foods', ['usda_food_id'], ['id'])
        batch_op.drop_column('vitamin_a_unit')
        batch_op.drop_column('sugars_per_serve')
        batch_op.drop_column('cholesterol_per_100')
        batch_op.drop_column('energy_per_serve_kj')
        batch_op.drop_column('trans_fat_per_serve')
        batch_op.drop_column('sugars_per_100')
        batch_op.drop_column('energy_per_100_cal')
        batch_op.drop_column('polyunsaturated_fat_per_serve')
        batch_op.drop_column('phosphorus_per_100')
        batch_op.drop_column('ingredients_list')
        batch_op.drop_column('dietary_fibre_per_serve')
        batch_op.drop_column('vitamin_b12_rdi_percent')
        batch_op.drop_column('fat_per_100')
        batch_op.drop_column('servings_per_pack')
        batch_op.drop_column('trans_fat_per_100')
        batch_op.drop_column('calcium_per_serve')
        batch_op.drop_column('riboflavin_b2_rdi_percent')
        batch_op.drop_column('polyunsaturated_fat_per_100')
        batch_op.drop_column('saturated_fat_per_100')
        batch_op.drop_column('vitamin_d_per_serve')
        batch_op.drop_column('lactose_per_100')
        batch_op.drop_column('may_contain_allergens')
        batch_op.drop_column('cholesterol_per_serve')
        batch_op.drop_column('calcium_per_100')
        batch_op.drop_column('carbohydrate_per_serve')
        batch_op.drop_column('vitamin_a_per_serve')
        batch_op.drop_column('energy_per_serve_cal')
        batch_op.drop_column('saturated_fat_per_serve')
        batch_op.drop_column('sodium_per_serve')
        batch_op.drop_column('riboflavin_b2_per_100')
        batch_op.drop_column('potassium_per_100')
        batch_op.drop_column('carbohydrate_per_100')
        batch_op.drop_column('riboflavin_b2_unit')
        batch_op.drop_column('vitamin_d_per_100')
        batch_op.drop_column('phosphorus_per_serve')
        batch_op.drop_column('contains_allergens')
        batch_op.drop_column('vitamin_b12_per_serve')
        batch_op.drop_column('dietary_fibre_per_100')
        batch_op.drop_column('galactose_per_serve')
        batch_op.drop_column('potassium_per_serve')
        batch_op.drop_column('vitamin_b12_unit')
        batch_op.drop_column('lactose_per_serve')
        batch_op.drop_column('serving_size')
        batch_op.drop_column('galactose_per_100')
        batch_op.drop_column('vitamin_a_per_100')
        batch_op.drop_column('vitamin_d_rdi_percent')
        batch_op.drop_column('monounsaturated_fat_per_100')
        batch_op.drop_column('vitamin_a_rdi_percent')
        batch_op.drop_column('calcium_rdi_percent')
        batch_op.drop_column('phosphorus_rdi_percent')
        batch_op.drop_column('energy_per_100_kj')
        batch_op.drop_column('where_to_buy')
        batch_op.drop_column('vitamin_b12_per_100')
        batch_op.drop_column('riboflavin_b2_per_serve')
        batch_op.drop_column('fat_per_serve')
        batch_op.drop_column('sodium_per_100')
        batch_op.drop_column('protein_per_100')
        batch_op.drop_column('monounsaturated_fat_per_serve')
        batch_op.drop_column('protein_per_serve')
        batch_op.drop_column('health_star_rating')
        batch_op.drop_column('vitamin_d_unit')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vitamin_d_unit', sa.VARCHAR(length=20), server_default=sa.text('("mcg")'), nullable=True))
        batch_op.add_column(sa.Column('health_star_rating', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('protein_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('monounsaturated_fat_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('protein_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('sodium_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('fat_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('riboflavin_b2_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b12_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('where_to_buy', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('energy_per_100_kj', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('phosphorus_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('calcium_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('vitamin_a_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('monounsaturated_fat_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_d_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('vitamin_a_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('galactose_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('serving_size', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('lactose_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b12_unit', sa.VARCHAR(length=20), server_default=sa.text('("mcg")'), nullable=True))
        batch_op.add_column(sa.Column('potassium_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('galactose_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('dietary_fibre_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b12_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('contains_allergens', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('phosphorus_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_d_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('riboflavin_b2_unit', sa.VARCHAR(length=20), server_default=sa.text('("mg")'), nullable=True))
        batch_op.add_column(sa.Column('carbohydrate_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('potassium_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('riboflavin_b2_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('sodium_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('saturated_fat_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('energy_per_serve_cal', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_a_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('carbohydrate_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('calcium_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('may_contain_allergens', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('lactose_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_d_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('saturated_fat_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('polyunsaturated_fat_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('riboflavin_b2_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('calcium_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('trans_fat_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('servings_per_pack', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fat_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_b12_rdi_percent', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('dietary_fibre_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('ingredients_list', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('phosphorus_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('polyunsaturated_fat_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('energy_per_100_cal', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('sugars_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('trans_fat_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('energy_per_serve_kj', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol_per_100', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('sugars_per_serve', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_a_unit', sa.VARCHAR(length=20), server_default=sa.text('("mcg")'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('dao_blocker',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('histamine_liberator',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    with op.batch_alter_table('educational_content', schema=None) as batch_op:
        batch_op.alter_column('chapter_number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
